DELETE FROM CHIAMATA;
DELETE FROM FTP;
DELETE FROM VNC;
DELETE FROM CHAT;
DELETE FROM SESSIONE;
DELETE FROM RICHIESTA;
DELETE FROM PARAMETRO;
DELETE FROM CONNESSIONE;
ALTER TABLE CHIAMATA AUTO_INCREMENT = 1;
ALTER TABLE FTP AUTO_INCREMENT = 1;
ALTER TABLE VNC AUTO_INCREMENT = 1;
ALTER TABLE CHAT AUTO_INCREMENT = 1;
ALTER TABLE SESSIONE AUTO_INCREMENT = 1;
ALTER TABLE RICHIESTA AUTO_INCREMENT = 1;
ALTER TABLE CONNESSIONE AUTO_INCREMENT = 1;

