CREATE DATABASE `jada` /*!40100 DEFAULT CHARACTER SET utf8 */;

/*
 *     D A T I   B A S E :
 *     regione
 *     cliente
 *     coda
 */
CREATE TABLE `regione` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=utf8;

CREATE TABLE `cliente` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) DEFAULT NULL,
  `ID_REGIONE` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_REGIONE_idx` (`ID_REGIONE`),
  CONSTRAINT `FK_CLIENTE_REGIONE` FOREIGN KEY (`ID_REGIONE`) REFERENCES `regione` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE `coda` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) NOT NULL,
  `ID_PADRE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CODA_CODA_idx` (`ID_PADRE`),
  CONSTRAINT `FK_CODA_CODA` FOREIGN KEY (`ID_PADRE`) REFERENCES `coda` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

/*
 *     M A N A G E R : 
 *     manager
 *     manager_coda
 */
CREATE TABLE `manager` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) NOT NULL,
  `USERNAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `MAIL` varchar(45) NOT NULL,
  `TELEFONO` varchar(45) DEFAULT NULL,
  `CELLULARE` varchar(45) DEFAULT NULL,
  `USA_AUDIO` int(1) NOT NULL DEFAULT '0',
  `AREA` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `manager_coda` (
  `ID_MANAGER` int(11) NOT NULL,
  `ID_CODA` int(11) NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DEFAULT` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `FK_MANAGER_idx` (`ID_MANAGER`),
  KEY `FK_CODA_idx` (`ID_CODA`),
  CONSTRAINT `FK_MC_CODA` FOREIGN KEY (`ID_CODA`) REFERENCES `coda` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_MC_MANAGER` FOREIGN KEY (`ID_MANAGER`) REFERENCES `manager` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*
 *     A G E N T :
 *     agent
 */
CREATE TABLE `agent` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) NOT NULL,
  `MAIL` varchar(45) DEFAULT NULL,
  `TELEFONO` varchar(45) DEFAULT NULL,
  `ID_CLIENTE` int(11) NOT NULL,
  `CELLULARE` varchar(45) DEFAULT NULL,
  `USA_AUDIO` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `FK_CLIENTE_idx` (`ID_CLIENTE`),
  CONSTRAINT `FK_AGENT_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

/*
 *     S E S S I O N E :
 *     connessione
 *     parametro
 *     richiesta
 *     sessione
 */
CREATE TABLE `connessione` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INDIRIZZO_IP` varchar(16) NOT NULL,
  `DATA_INIZIO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA_FINE` datetime DEFAULT NULL,
  `ID_AGENT` int(11) DEFAULT NULL,
  `ID_MANAGER` int(11) DEFAULT NULL,
  `USA_AUDIO` int(11) DEFAULT NULL,
  `STATO` varchar(1) NOT NULL,
  `INDIRIZZO_IP_HOST` varchar(16) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_AGENT_idx` (`ID_AGENT`),
  KEY `FK_MANAGER_idx` (`ID_MANAGER`),
  CONSTRAINT `FK_CONNESSIONE_AGENT` FOREIGN KEY (`ID_AGENT`) REFERENCES `agent` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_CONNESSIONE_MANAGER` FOREIGN KEY (`ID_MANAGER`) REFERENCES `manager` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=268 DEFAULT CHARSET=utf8;

CREATE TABLE `parametro` (
  `ID_CONNESSIONE` int(11) NOT NULL,
  `SEZIONE` varchar(45) NOT NULL,
  `NOME` varchar(45) NOT NULL,
  `VALORE` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID_CONNESSIONE`,`SEZIONE`,`NOME`),
  KEY `FK_PARAMETRO_CONNESSIONE_idx` (`ID_CONNESSIONE`),
  CONSTRAINT `FK_PARAMETRO_CONNESSIONE` FOREIGN KEY (`ID_CONNESSIONE`) REFERENCES `connessione` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `richiesta` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATO` varchar(1) NOT NULL,
  `ID_CODA` int(11) NOT NULL,
  `DESCRIZIONE` varchar(1024) DEFAULT NULL,
  `DATA_INIZIO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA_FINE` datetime DEFAULT NULL,
  `ID_AGENT` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RICHIESTA_AGENT_idx` (`ID_AGENT`),
  CONSTRAINT `FK_RICHIESTA_AGENT` FOREIGN KEY (`ID_AGENT`) REFERENCES `agent` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8;

CREATE TABLE `sessione` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CONNESSIONE_AGENT` int(11) DEFAULT NULL,
  `ID_CONNESSIONE_MANAGER` int(11) DEFAULT NULL,
  `STATO` varchar(1) NOT NULL,
  `DATA_INIZIO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA_FINE` datetime DEFAULT NULL,
  `ID_RICHIESTA` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SESSIONE_AGENT_idx` (`ID_CONNESSIONE_AGENT`),
  KEY `FK_SESSIONE_MANAGER_idx` (`ID_CONNESSIONE_MANAGER`),
  KEY `FK_SESSIONE_RICHIESTA_idx` (`ID_RICHIESTA`),
  CONSTRAINT `FK_SESSIONE_AGENT` FOREIGN KEY (`ID_CONNESSIONE_AGENT`) REFERENCES `connessione` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_SESSIONE_MANAGER` FOREIGN KEY (`ID_CONNESSIONE_MANAGER`) REFERENCES `connessione` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_SESSIONE_RICHIESTA` FOREIGN KEY (`ID_RICHIESTA`) REFERENCES `richiesta` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*
 *     S E R V I Z I :
 *     chat
 *     chiamata
 *     ftp
 *     vnc
 */
CREATE TABLE `chat` (
  `ID_RICHIESTA` int(11) NOT NULL,
  `DATA_INVIO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MITTENTE` varchar(1) NOT NULL,
  `TESTO` varchar(512) DEFAULT NULL,
  `DATA_RICEZIONE` datetime DEFAULT NULL,
  KEY `FK_CHAT_RICHIESTA_idx` (`ID_RICHIESTA`),
  CONSTRAINT `FK_CHAT_RICHIESTA` FOREIGN KEY (`ID_RICHIESTA`) REFERENCES `richiesta` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `chiamata` (
  `ID_SESSIONE` int(11) NOT NULL,
  `USA_AUDIO` varchar(1) NOT NULL,
  `USA_VIDEO` varchar(1) NOT NULL,
  `DATA_INIZIO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA_FINE` datetime DEFAULT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  KEY `FK_MEDIA_SUPPORTO_idx` (`ID_SESSIONE`),
  CONSTRAINT `FK_MEDIA_SESSIONE` FOREIGN KEY (`ID_SESSIONE`) REFERENCES `sessione` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ftp` (
  `ID_SESSIONE` int(11) NOT NULL,
  `DIREZIONE` varchar(5) NOT NULL,
  `DA_FILE` varchar(256) NOT NULL,
  `A_FILE` varchar(256) NOT NULL,
  `DATA_INIZIO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA_FINE` datetime DEFAULT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  KEY `FK_FTP_SUPPORTO_idx` (`ID_SESSIONE`),
  CONSTRAINT `FK_FTP_SESSIONE` FOREIGN KEY (`ID_SESSIONE`) REFERENCES `sessione` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vnc` (
  `ID_SESSIONE` int(11) NOT NULL,
  `DATA_INIZIO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA_FINE` datetime DEFAULT NULL,
  `CARTELLA_REGISTRAZIONE` varchar(128) DEFAULT NULL,
  `STATO_REGISTRAZIONE` int(1) DEFAULT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  KEY `FK_VNC_SUPPORTO_idx` (`ID_SESSIONE`),
  CONSTRAINT `FK_VNC_SESSIONE` FOREIGN KEY (`ID_SESSIONE`) REFERENCES `sessione` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;
